Add ui tests for functions
rust-lang/a-mir-formality pull request #137
Opened 2023-09-10 18:58 UTC by obeis

Updates #99

cc @oli-obk

2023-09-10 19:16 UTC, compiler-errors commented on tests/ui/fn/ok.stderr
> +    1: failed to parse [
This is a parser error. Have you looked at the other tests that demonstrate the difference in a-mir-formality syntax?

2023-09-10 19:18 UTC, compiler-errors commented on tests/ui/fn/ok.🔬
> +        fn with_return() -> &str {}
For the record, `with_return` isn't valid Rust:

```
error[E0106]: missing lifetime specifier
 --> src/lib.rs:3:29
  |
3 |         fn with_return() -> &str {}
  |                             ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
  |
3 |         fn with_return() -> &'static str {}
```

2023-09-10 19:32 UTC, oli-obk requested changes

2023-09-10 19:32 UTC, oli-obk commented on tests/ui/fn/ok.🔬
> +        fn no_args() {}
```suggestion
        fn no_args<>() {}
```

I'd guess you need sth like this, but not sure how formality parses functions

2023-09-10 19:32 UTC, oli-obk commented on tests/ui/fn/ok.🔬
> +        fn with_return() -> String {}
Formality won't know this type, it has no standard library

2023-09-10 19:32 UTC, oli-obk commented on tests/ui/fn/ok.🔬
> +        fn return_multi(a: i32, b: i32) -> (i32, i32) {}
Not sure formality knows tuples

2023-09-11 10:15 UTC, oli-obk commented
I haven't forgotten about this 😆

2023-09-11 10:16 UTC, oli-obk commented on tests/ui/fn/ok.stderr
> +Error: failed to prove {@ wf((rigid &(shared) !lt_2 !ty_1))} given {}, got {}
about which function is this error?

maybe create one test per failing function.

2023-09-11 10:19 UTC, oli-obk commented on tests/ui/fn/ok.🔬
> +        fn one_return<ty T, lt l, ty U>(&l T) -> U where [] { trusted }
Leave a comment explaining what Rust signature this signature is equivalent to. this is `fn foo<'a, T, U>(_: &'a T) -> U`, and previously you had different functions.

Also leave a comment explaining what the tests are testing, as I can't tell from the test.

2023-09-18 14:25 UTC, nikomatsakis approved these changes

2023-09-18 14:25 UTC, merged